# Blank SQL Notebook

#### Import Libraries & Database

In [22]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [23]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
AND table_type = 'BASE TABLE';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [24]:
%%sql

SELECT * FROM sales LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00

In [25]:
%%sql

SELECT *
FROM customer
LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14

In [26]:
%%sql

SELECT *
FROM product
LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3

In [27]:
%%sql

SELECT *
FROM store
LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None

In [28]:
%%sql

SELECT *
FROM currencyexchange
LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82

In [29]:
%%sql

SELECT *
FROM date
LIMIT 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2

In [30]:
%%sql

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name = 'sales';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13 rows affected.

     column_name          data_type
0   exchangerate   double precision
1     linenumber            integer
2      orderdate               date
3   deliverydate               date
4    customerkey            integer
5       storekey            integer
6     productkey            integer
7       quantity            integer
8      unitprice   double precision
9       netprice   double precision
10      unitcost   double precision
11      orderkey            integer
12  currencycode  character varying

In [31]:
%%sql

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name = 'customer';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

      column_name          data_type
0     customerkey            integer
1      geoareakey            integer
2         startdt               date
3           enddt               date
4        birthday               date
5             age            integer
6        latitude   double precision
7       longitude   double precision
8   middleinitial  character varying
9         surname  character varying
10  streetaddress  character varying
11           city  character varying
12          state  character varying
13      statefull  character varying
14        zipcode  character varying
15        country  character varying
16    countryfull  character varying
17        company  character varying
18        vehicle  character varying
19     occupation  character varying
20      continent  character varying
21         gender  character varying
22          title  character varying
23      givenname  character varying

Calculate Net Revenue for customer generating more than $1000 after Jan 1st 2020

In [32]:
%%sql

SELECT
    s.orderdate,
    c.givenname,
    c.surname,
    c.countryfull,
    c.continent,
    s.quantity * s.netprice * s.exchangerate AS net_revenue,
    p.productkey,
    p.productname,
    p.subcategoryname,
    CASE
        WHEN s.quantity * s.netprice * s.exchangerate > 1000
        THEN 'high'
        ELSE 'low'
    END AS high_low
FROM sales s
LEFT JOIN customer c
ON s.customerkey = c.customerkey
LEFT JOIN product p
ON s.productkey = p.productkey
WHERE orderdate::DATE >= '2020-01-01';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,givenname,surname,countryfull,continent,net_revenue,productkey,productname,subcategoryname,high_low
0,2020-01-01,David,Stone,United States,North America,3075.80,1051,"A. Datum SLR Camera 35"" M358 Silver",Digital SLR Cameras,high
1,2020-01-01,David,Stone,United States,North America,444.34,1709,MGS Gears of War M170,Download Games,low
2,2020-01-01,David,Stone,United States,North America,1187.73,457,WWI Desktop PC1.60 E1600 White,Desktops,high
3,2020-01-01,David,Stone,United States,North America,36.78,1385,Contoso Multi-line phones M30 Grey,Home & Office Phones,low
4,2020-01-01,David,Stone,United States,North America,4.45,1665,MGS Hand Games for 12-16 boys E600 Yellow,Boxed Games,low
...,...,...,...,...,...,...,...,...,...,...
124446,2024-04-20,Guus,Doodeman,Netherlands,Europe,14.35,849,Contoso Ultraportable Neoprene Sleeve E30 Green,Computers Accessories,low
124447,2024-04-20,Guus,Doodeman,Netherlands,Europe,261.32,1651,Contoso DVD 9-Inch Player Portable M300 Silver,Movie DVD,low
124448,2024-04-20,Michael,Wilson,Canada,North America,147.78,1575,SV DVD Player M140 Gold,Movie DVD,low
124449,2024-04-20,Michael,Wilson,Canada,North America,2019.62,415,Proseware Laptop8.9 E089 White,Laptops,high
124450,2024-04-20,Michael,Wilson,Canada,North America,56.83,1693,SV Hand Games men M30 Black,Boxed Games,low

Practice Question 1

Display:

Order Date
Customer Name
Country
Product Name
Net Revenue

Conditions:

Revenue > 500
Customer from Europe

Sort by highest revenue.

In [33]:
%%sql

SELECT
    s.orderdate,
    c.givenname,
    c.surname,
    c.countryfull,
    p.productname,
    s.quantity * s.netprice * s.exchangerate AS net_revenue
FROM sales s
LEFT JOIN customer c
ON s.customerkey = c.customerkey
LEFT JOIN product p
ON s.productkey = p.productkey
WHERE s.quantity * s.netprice * s.exchangerate > 500
AND c.continent = 'Europe'
ORDER BY net_revenue DESC;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

25511 rows affected.

,orderdate,givenname,surname,countryfull,productname,net_revenue
0,2019-05-25,Steffen,Metzger,Germany,Proseware Projector 1080p LCD86 White,41029.55
1,2019-11-26,Janina,Unger,Germany,Proseware Projector 1080p DLP86 Silver,40818.47
2,2018-09-04,Dylan,Brennan,United Kingdom,WWI Projector 1080p DLP86 Black,35036.93
3,2016-08-31,Stefan,Jung,Germany,Proseware Projector 1080p LCD86 Silver,33552.89
4,2019-09-17,Oliver,Louineaux,France,Proseware Projector 1080p DLP86 Silver,31730.55
...,...,...,...,...,...,...
25506,2022-07-02,Luke,Palmer,United Kingdom,Contoso DVD 14-Inch Player Portable L100 White,500.04
25507,2022-01-14,Jens,Amsel,Germany,WWI Floor Lamp X115 Black,500.04
25508,2022-11-17,Rianka,Arentsen,Netherlands,Contoso Touch Screen Phones - CRT M11 Black,500.02
25509,2024-01-03,Monika,Loewe,Germany,Litware Microwave 2.2CuFt M125 Red,500.02
25510,2024-01-02,Ulrike,Finkel,Germany,The Phone Company Sharp Touch Screen Phones M9...,500.02

COUNT (Distinct) Review -
 Total Customers per day in 2023

In [34]:
%%sql
select orderdate, count(distinct customerkey) as total_customers
from sales
where orderdate::DATE between '2023-01-01' and '2023-12-31'
group by orderdate
order by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

Pivot with COUNT() - Daily Customers by Region

In [35]:
%%sql
select distinct continent from customer;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [36]:
%%sql
select s.orderdate, count(distinct s.customerkey) as total_customers,
count (distinct case when c.continent='Europe' then c.customerkey end) as eu_customers,
count (distinct case when c.continent='North America' then c.customerkey end) as na_customers,
count (distinct case when c.continent='Australia' then c.customerkey end) as au_customers
from sales s
left join customer c on s.customerkey=c.customerkey
where s.orderdate::DATE between '2023-01-01' and '2023-12-31'
group by s.orderdate
order by s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_customers  na_customers  au_customers
0    2023-01-01               12             6             5             1
1    2023-01-02               49            15            31             3
2    2023-01-03               64            17            44             3
3    2023-01-04               78            28            46             4
4    2023-01-05               87            22            57             8
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26            41             6
360  2023-12-28               75            24            44             7
361  2023-12-29               55            19            32             4
362  2023-12-30               91            25            50            16
363  2023-12-31                9             1             8             0

[364 rows x 5 columns]

COUNT(DISTINCT CASE WHEN condition THEN column_name END) AS alias

Total Net Revenue by category (2022 vs 2023)

In [37]:
%%sql

SELECT
    p.categoryname,
    sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as total_net_revenue_2022,
    sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as total_net_revenue_2023
FROM sales s
LEFT JOIN product p on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

Pivot with Sum -- sum (case when condiition then column else 0 end) as alias

Categorize


*   "High value order" if quantity >=2 and netprice>=50
*   "Standard orders" otherwise

In [38]:
%%sql
select orderdate, quantity, netprice,
case when quantity >=2 and netprice>=50 then 'high_value_order'
else 'standard_order'end as order_type
from sales limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice        order_type
0  2015-01-01         1     98.97    standard_order
1  2015-01-01         1    659.78    standard_order
2  2015-01-01         2     54.38  high_value_order
3  2015-01-01         4    286.69  high_value_order
4  2015-01-01         7    135.75  high_value_order
5  2015-01-01         3    434.30  high_value_order
6  2015-01-01         1     58.73    standard_order
7  2015-01-01         3     74.99  high_value_order
8  2015-01-01         2    113.57  high_value_order
9  2015-01-01         1    499.45    standard_order

Categorize


*   "Multiple High value items" if quantity >=2 and netprice>=100
*   "Single High value items" if netprice>=100

*   "Multiple standard items" if quantity>=2
*   "Single standard item" otherwise

In [39]:
%%sql
select orderdate, quantity, netprice,
case
  when quantity >=2 and netprice>=100 then 'multiple_high_value_items'
  when netprice=100 then 'single_high_value_items'
  when quantity >=2 then 'multiple_standard_items'
else 'single_standard_item'end as order_type
from sales limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       single_standard_item
1  2015-01-01         1    659.78       single_standard_item
2  2015-01-01         2     54.38    multiple_standard_items
3  2015-01-01         4    286.69  multiple_high_value_items
4  2015-01-01         7    135.75  multiple_high_value_items
5  2015-01-01         3    434.30  multiple_high_value_items
6  2015-01-01         1     58.73       single_standard_item
7  2015-01-01         3     74.99    multiple_standard_items
8  2015-01-01         2    113.57  multiple_high_value_items
9  2015-01-01         1    499.45       single_standard_item

Using AND for multiple operations

In [40]:
%%sql
# for median
SELECT
    PERCENTILE_CONT(0.5)
    WITHIN GROUP (
        ORDER BY (s.quantity * s.netprice * s.exchangerate)
    ) AS median
FROM sales s
WHERE s.orderdate::DATE BETWEEN '2022-01-01' AND '2023-12-31';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

Conditional Aggregation

In [47]:
%%sql

SELECT p.categoryname as category,
SUM(CASE when (s.quantity * s.netprice * s.exchangerate)<398
then (s.quantity * s.netprice * s.exchangerate) end) as low_revenue,
SUM(CASE when (s.quantity * s.netprice * s.exchangerate)>=398
then (s.quantity * s.netprice * s.exchangerate) end) as high_revenue
FROM sales s
LEFT JOIN product p on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  low_revenue  high_revenue
0                          Audio   1759699.82    3553198.29
1        Cameras and camcorders     829242.04   17691118.62
2                    Cell phones   2862254.35   29762011.36
3                      Computers   2204185.96   88414836.09
4                 Games and Toys   1254038.18     414535.96
5                Home Appliances   1095190.74   25512054.79
6  Music, Movies and Audio Books   2862001.70    7726309.30
7                   TV and Video    980860.35   19486001.03

Segmenting the above for 2022 and 2023 by using AND in case when (condition)

In [49]:
%%sql

SELECT p.categoryname as category,
SUM(CASE when (s.quantity * s.netprice * s.exchangerate)<398
and s.orderdate between '2022-01-01' and '2022-12-31'
then (s.quantity * s.netprice * s.exchangerate) end) as low_revenue_2022,
SUM(CASE when (s.quantity * s.netprice * s.exchangerate)>=398
and s.orderdate between '2022-01-01' and '2022-12-31'
then (s.quantity * s.netprice * s.exchangerate) end) as high_revenue_2022,
SUM(CASE when (s.quantity * s.netprice * s.exchangerate)<398
and s.orderdate between '2023-01-01' and '2023-12-31'
then (s.quantity * s.netprice * s.exchangerate) end) as low_revenue_2023,
SUM(CASE when (s.quantity * s.netprice * s.exchangerate)>=398
and s.orderdate between '2023-01-01' and '2023-12-31'
then (s.quantity * s.netprice * s.exchangerate) end) as high_revenue_2023
FROM sales s
LEFT JOIN product p on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_revenue_2022,high_revenue_2022,low_revenue_2023,high_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87